// Code generated by goctl. DO NOT EDIT.
// Source: sdbrpc.proto

package sdbrpcclient

import (
	"context"

	"statedbl/sdbrpc/sdbrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = sdbrpc.Request
	Response = sdbrpc.Response

	Sdbrpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSdbrpc struct {
		cli zrpc.Client
	}
)

func NewSdbrpc(cli zrpc.Client) Sdbrpc {
	return &defaultSdbrpc{
		cli: cli,
	}
}

func (m *defaultSdbrpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := sdbrpc.NewSdbrpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
