// Code generated by goctl. DO NOT EDIT.
// Source: sdb.proto

package server

import (
	"context"

	"statedbl/service/sdb/rpc/internal/logic"
	"statedbl/service/sdb/rpc/internal/svc"
	"statedbl/service/sdb/rpc/types/sdb"
)

type SdbServer struct {
	svcCtx *svc.ServiceContext
	sdb.UnimplementedSdbServer
}

func NewSdbServer(svcCtx *svc.ServiceContext) *SdbServer {
	return &SdbServer{
		svcCtx: svcCtx,
	}
}

func (s *SdbServer) CreateAccount(ctx context.Context, in *sdb.CreateAccountRequest) (*sdb.CreateAccountResponse, error) {
	l := logic.NewCreateAccountLogic(ctx, s.svcCtx)
	return l.CreateAccount(in)
}

func (s *SdbServer) SubBalance(ctx context.Context, in *sdb.SubBalanceRequest) (*sdb.SubBalanceResponse, error) {
	l := logic.NewSubBalanceLogic(ctx, s.svcCtx)
	return l.SubBalance(in)
}

func (s *SdbServer) AddBalance(ctx context.Context, in *sdb.AddBalanceRequest) (*sdb.AddBalanceResponse, error) {
	l := logic.NewAddBalanceLogic(ctx, s.svcCtx)
	return l.AddBalance(in)
}

func (s *SdbServer) GetBalance(ctx context.Context, in *sdb.GetBalanceRequest) (*sdb.GetBalanceResponse, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *SdbServer) Suicide(ctx context.Context, in *sdb.SuicideRequest) (*sdb.SuicideResponse, error) {
	l := logic.NewSuicideLogic(ctx, s.svcCtx)
	return l.Suicide(in)
}

func (s *SdbServer) HasSuicided(ctx context.Context, in *sdb.HasSuicidedRequest) (*sdb.HasSuicidedResponse, error) {
	l := logic.NewHasSuicidedLogic(ctx, s.svcCtx)
	return l.HasSuicided(in)
}

func (s *SdbServer) GetNonce(ctx context.Context, in *sdb.GetNonceRequest) (*sdb.GetNonceResponse, error) {
	l := logic.NewGetNonceLogic(ctx, s.svcCtx)
	return l.GetNonce(in)
}

func (s *SdbServer) SetNonce(ctx context.Context, in *sdb.SetNonceRequest) (*sdb.SetNonceResponse, error) {
	l := logic.NewSetNonceLogic(ctx, s.svcCtx)
	return l.SetNonce(in)
}

func (s *SdbServer) GetCodeHash(ctx context.Context, in *sdb.GetCodeHashRequest) (*sdb.GetCodeHashResponse, error) {
	l := logic.NewGetCodeHashLogic(ctx, s.svcCtx)
	return l.GetCodeHash(in)
}

func (s *SdbServer) GetCode(ctx context.Context, in *sdb.GetCodeRequest) (*sdb.GetCodeResponse, error) {
	l := logic.NewGetCodeLogic(ctx, s.svcCtx)
	return l.GetCode(in)
}

func (s *SdbServer) SetCode(ctx context.Context, in *sdb.SetCodeRequest) (*sdb.SetCodeResponse, error) {
	l := logic.NewSetCodeLogic(ctx, s.svcCtx)
	return l.SetCode(in)
}

func (s *SdbServer) GetCodeSize(ctx context.Context, in *sdb.GetCodeSizeRequest) (*sdb.GetCodeSizeResponse, error) {
	l := logic.NewGetCodeSizeLogic(ctx, s.svcCtx)
	return l.GetCodeSize(in)
}

func (s *SdbServer) AddRefund(ctx context.Context, in *sdb.AddRefundRequest) (*sdb.AddRefundResponse, error) {
	l := logic.NewAddRefundLogic(ctx, s.svcCtx)
	return l.AddRefund(in)
}

func (s *SdbServer) SubRefund(ctx context.Context, in *sdb.SubRefundRequest) (*sdb.SubRefundResponse, error) {
	l := logic.NewSubRefundLogic(ctx, s.svcCtx)
	return l.SubRefund(in)
}

func (s *SdbServer) GetRefund(ctx context.Context, in *sdb.GetRefundRequest) (*sdb.GetRefundResponse, error) {
	l := logic.NewGetRefundLogic(ctx, s.svcCtx)
	return l.GetRefund(in)
}

func (s *SdbServer) GetTransientState(ctx context.Context, in *sdb.GetTransientStateRequest) (*sdb.GetTransientStateResponse, error) {
	l := logic.NewGetTransientStateLogic(ctx, s.svcCtx)
	return l.GetTransientState(in)
}

func (s *SdbServer) SetTransientState(ctx context.Context, in *sdb.SetTransientStateRequest) (*sdb.SetTransientStateResponse, error) {
	l := logic.NewSetTransientStateLogic(ctx, s.svcCtx)
	return l.SetTransientState(in)
}

func (s *SdbServer) Exist(ctx context.Context, in *sdb.ExistRequest) (*sdb.ExistResponse, error) {
	l := logic.NewExistLogic(ctx, s.svcCtx)
	return l.Exist(in)
}

func (s *SdbServer) Empty(ctx context.Context, in *sdb.EmptyRequest) (*sdb.EmptyResponse, error) {
	l := logic.NewEmptyLogic(ctx, s.svcCtx)
	return l.Empty(in)
}

func (s *SdbServer) AddressInAccessList(ctx context.Context, in *sdb.AddressInAccessListRequest) (*sdb.AddressInAccessListResponse, error) {
	l := logic.NewAddressInAccessListLogic(ctx, s.svcCtx)
	return l.AddressInAccessList(in)
}

func (s *SdbServer) SlotInAccessList(ctx context.Context, in *sdb.SlotInAccessListRequest) (*sdb.SlotInAccessListResponse, error) {
	l := logic.NewSlotInAccessListLogic(ctx, s.svcCtx)
	return l.SlotInAccessList(in)
}

func (s *SdbServer) AddAddressToAccessList(ctx context.Context, in *sdb.AddAddressToAccessListRequest) (*sdb.AddAddressToAccessListResponse, error) {
	l := logic.NewAddAddressToAccessListLogic(ctx, s.svcCtx)
	return l.AddAddressToAccessList(in)
}

func (s *SdbServer) AddSlotToAccessList(ctx context.Context, in *sdb.AddSlotToAccessListRequest) (*sdb.AddSlotToAccessListResponse, error) {
	l := logic.NewAddSlotToAccessListLogic(ctx, s.svcCtx)
	return l.AddSlotToAccessList(in)
}

func (s *SdbServer) RevertToSnapshot(ctx context.Context, in *sdb.RevertToSnapshotRequest) (*sdb.RevertToSnapshotResponse, error) {
	l := logic.NewRevertToSnapshotLogic(ctx, s.svcCtx)
	return l.RevertToSnapshot(in)
}

func (s *SdbServer) Snapshot(ctx context.Context, in *sdb.SnapshotRequest) (*sdb.SnapshotResponse, error) {
	l := logic.NewSnapshotLogic(ctx, s.svcCtx)
	return l.Snapshot(in)
}

func (s *SdbServer) AddPreimage(ctx context.Context, in *sdb.AddPreimageRequest) (*sdb.AddPreimageResponse, error) {
	l := logic.NewAddPreimageLogic(ctx, s.svcCtx)
	return l.AddPreimage(in)
}

func (s *SdbServer) AddLog(ctx context.Context, in *sdb.AddLogRequest) (*sdb.AddLogRespond, error) {
	l := logic.NewAddLogLogic(ctx, s.svcCtx)
	return l.AddLog(in)
}

func (s *SdbServer) Prepare(ctx context.Context, in *sdb.PrepareRequest) (*sdb.PrepareRespond, error) {
	l := logic.NewPrepareLogic(ctx, s.svcCtx)
	return l.Prepare(in)
}

func (s *SdbServer) GetCommittedState(ctx context.Context, in *sdb.GetCommittedStateRequest) (*sdb.GetCommittedStateResponse, error) {
	l := logic.NewGetCommittedStateLogic(ctx, s.svcCtx)
	return l.GetCommittedState(in)
}

func (s *SdbServer) GetState(ctx context.Context, in *sdb.GetStateRequest) (*sdb.GetStateResponse, error) {
	l := logic.NewGetStateLogic(ctx, s.svcCtx)
	return l.GetState(in)
}

func (s *SdbServer) SetState(ctx context.Context, in *sdb.SetStateRequest) (*sdb.SetStateResponse, error) {
	l := logic.NewSetStateLogic(ctx, s.svcCtx)
	return l.SetState(in)
}
