// Code generated by goctl. DO NOT EDIT.
// Source: sdb.proto

package server

import (
	"context"

	"statedbl/service/sdb/rpc/internal/logic"
	"statedbl/service/sdb/rpc/internal/svc"
	"statedbl/service/sdb/rpc/types/sdb"
)

type SdbServer struct {
	svcCtx *svc.ServiceContext
	sdb.UnimplementedSdbServer
}

func NewSdbServer(svcCtx *svc.ServiceContext) *SdbServer {
	return &SdbServer{
		svcCtx: svcCtx,
	}
}

func (s *SdbServer) Suicide(ctx context.Context, in *sdb.SuicideRequest) (*sdb.SuicideResponse, error) {
	l := logic.NewSuicideLogic(ctx, s.svcCtx)
	return l.Suicide(in)
}
