// Code generated by goctl. DO NOT EDIT.
// Source: sdb.proto

package server

import (
	"context"

	"statedbl/service/sdb/rpc/internal/logic"
	"statedbl/service/sdb/rpc/internal/svc"
	"statedbl/service/sdb/rpc/types/sdb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	sdb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Suicide(ctx context.Context, in *sdb.SuicideRequest) (*sdb.SuicideResponse, error) {
	l := logic.NewSuicideLogic(ctx, s.svcCtx)
	return l.Suicide(in)
}
