// Code generated by goctl. DO NOT EDIT.
// Source: sdb.proto

package user

import (
	"context"

	"statedbl/service/sdb/rpc/types/sdb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SuicideRequest  = sdb.SuicideRequest
	SuicideResponse = sdb.SuicideResponse

	User interface {
		Suicide(ctx context.Context, in *SuicideRequest, opts ...grpc.CallOption) (*SuicideResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Suicide(ctx context.Context, in *SuicideRequest, opts ...grpc.CallOption) (*SuicideResponse, error) {
	client := sdb.NewUserClient(m.cli.Conn())
	return client.Suicide(ctx, in, opts...)
}
