// Code generated by goctl. DO NOT EDIT.
// Source: sdbrpc.proto

package server

import (
	"context"

	"statedbl/sdbrpc/internal/logic"
	"statedbl/sdbrpc/internal/svc"
	"statedbl/sdbrpc/sdbrpc"
)

type SdbrpcServer struct {
	svcCtx *svc.ServiceContext
	sdbrpc.UnimplementedSdbrpcServer
}

func NewSdbrpcServer(svcCtx *svc.ServiceContext) *SdbrpcServer {
	return &SdbrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *SdbrpcServer) Ping(ctx context.Context, in *sdbrpc.Request) (*sdbrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
