// Code generated by goctl. DO NOT EDIT.
package types

type CreateAccountRequest struct {
	Addr string `json:"address"`
}

type CreateAccountResponse struct {
	Empty bool `json:"empty"`
}

type SubBalanceRequest struct {
	Addr   string `json:"address"`
	Amount int64  `json:"amount"`
}

type SubBalanceResponse struct {
	Empty bool `json:"empty"`
}

type AddBalanceRequest struct {
	Addr   string `json:"address"`
	Amount int64  `json:"amount"`
}

type AddBalanceResponse struct {
	Empty bool `json:"empty"`
}

type GetBalanceRequest struct {
	Addr string `json:"address"`
}

type GetBalanceResponse struct {
	Amount int64 `json:"amount"`
}

type SuicideRequest struct {
	Addr string `json:"address"`
}

type SuicideResponse struct {
	Is_suicide bool `json:"is_suicide"`
}
